# Objective - Write a docker-compose.yml for a Redis cache and a Node app.
# Give Redis a 'tmpfs' volume (because it's a cache!).
# Mount your local '/src' folder to the Node app using a bind mount.
# Map the Node app's port '3000' to the host.
# Run 'docker compose up -d'.

services:
  cache_layer:
    image: redis:latest
    volumes:
      - type: tmpfs
        target: /tmp

  app_layer:
    image: node:20-alpine
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./src
        target: /app/src
